acme_colog:
    resource: "@AcmeCologBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@UserBundle/Resources/Config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"
