services:
#    acme_colog.example:
#        class: Acme\CologBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    my.listener:
        class: Acme\CologBundle\EventListener\CalendarEventlistener
        tags:
            - { name: doctrine.CalendarEventListener, event: CalendarEventListener }
